### ISSUE TITLE
Cannot clone or push or pull to Azure DevOps repos

### ISSUE THREAD

**Issue by Valiante** [gbrac/gbrac.github.io#1]
First of all, please accept my apologies for contacting you in this manner - however you seem to be the only person on the entire internet to have encountered this same issue with which I am now faced.

https://github.com/microsoft/vscode/issues/138199

You requested for this issue to be closed citing BeyondTrust EPM as the root cause.   I too have found that disabling the service temporarily resolves the issue.  I was wondering if you would be kind enough to share the ultimate solution?

**Comment by gbrac** [comment]
Hi. No worries - glad to help, if I can. 
I have a workaround that appears to work. I configure git to not use the Windows Credential Manager store. I use this command to set git to use encrypted files stored at %USERPROFILE%\gcm\dpapi_store. This is the command:
**git config --global credential.credentialStore dpapi**

**Comment by Valiante** [comment]
Ah ok thanks - our developers already identified that workaround but are pushing for a permanent solution. Not to worry, and sincerely appreciate you coming back to me.
